In [19]:
import numpy as np

In [49]:
def pivot_matrix(A):
    m = A.shape[0]
    for j in range(m):
        row = max(range(j, m), key=lambda i: abs(A[i, j]))
        if j != row:
            A[[j, row]] = A[[row, j]]
    return A

In [53]:
def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    U = np.zeros_like(A)
    A = pivot_matrix(A)
    for j in range(n):
        L[j, j] = 1
        for i in range(j + 1):
            U[i][j] = A[i][j] - sum(L[i][k] * U[k][j] for k in range(i))
        for i in range(j, n):
            L[i][j] = (A[i][j] - sum(L[i][k] * U[k][j] for k in range(j))) / U[j][j]
    return A, L, U

In [56]:
A = np.array([[4, -1, 1], [4, -8, 1], [-2, 1, 5]])
b = np.array([7, -21, 15])
A, L, U = lu_decomposition(A)
print(A)
print(L)
print(U)
L * U

[[ 4 -1  1]
 [ 4 -8  1]
 [-2  1  5]]
[[1 0 0]
 [1 1 0]
 [0 0 1]]
[[ 4 -1  1]
 [ 0 -7  0]
 [ 0  0  5]]


array([[ 4,  0,  0],
       [ 0, -7,  0],
       [ 0,  0,  5]])